# modeling
size: [256, 256]
lambda_recon: 50
patch_level: 3
adv_loss_type: LS # CE, LS

# training
n_epochs: 200
batch_size: 8
gen_lr: 2.e-4
disc_lr: 1.e-4

# visualization and save
display_step: 500
n_images_row: 6 # number of images per row
record_step: 1000
print_step: 500